
package cn.com.zv2.stub.hello;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloServer", targetNamespace = "http://server.zv2.com.cn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloServer {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://server.zv2.com.cn/", className = "cn.com.zv2.stub.hello.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://server.zv2.com.cn/", className = "cn.com.zv2.stub.hello.SayHelloResponse")
    @Action(input = "http://server.zv2.com.cn/HelloServer/sayHelloRequest", output = "http://server.zv2.com.cn/HelloServer/sayHelloResponse")
    public String sayHello(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

}
