
package cn.com.zv2.stub.hello;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HelloServerService", targetNamespace = "http://server.zv2.com.cn/", wsdlLocation = "http://127.0.0.1/hello?wsdl")
public class HelloServerService
    extends Service
{

    private final static URL HELLOSERVERSERVICE_WSDL_LOCATION;
    private final static WebServiceException HELLOSERVERSERVICE_EXCEPTION;
    private final static QName HELLOSERVERSERVICE_QNAME = new QName("http://server.zv2.com.cn/", "HelloServerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1/hello?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HELLOSERVERSERVICE_WSDL_LOCATION = url;
        HELLOSERVERSERVICE_EXCEPTION = e;
    }

    public HelloServerService() {
        super(__getWsdlLocation(), HELLOSERVERSERVICE_QNAME);
    }

    public HelloServerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HELLOSERVERSERVICE_QNAME, features);
    }

    public HelloServerService(URL wsdlLocation) {
        super(wsdlLocation, HELLOSERVERSERVICE_QNAME);
    }

    public HelloServerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HELLOSERVERSERVICE_QNAME, features);
    }

    public HelloServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloServerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HelloServer
     */
    @WebEndpoint(name = "HelloServerPort")
    public HelloServer getHelloServerPort() {
        return super.getPort(new QName("http://server.zv2.com.cn/", "HelloServerPort"), HelloServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloServer
     */
    @WebEndpoint(name = "HelloServerPort")
    public HelloServer getHelloServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.zv2.com.cn/", "HelloServerPort"), HelloServer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HELLOSERVERSERVICE_EXCEPTION!= null) {
            throw HELLOSERVERSERVICE_EXCEPTION;
        }
        return HELLOSERVERSERVICE_WSDL_LOCATION;
    }

}
