
package cn.com.zv2.stub.person;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PersonServerService", targetNamespace = "http://server.zv2.com.cn/", wsdlLocation = "http://127.0.0.1:80/person?wsdl")
public class PersonServerService
    extends Service
{

    private final static URL PERSONSERVERSERVICE_WSDL_LOCATION;
    private final static WebServiceException PERSONSERVERSERVICE_EXCEPTION;
    private final static QName PERSONSERVERSERVICE_QNAME = new QName("http://server.zv2.com.cn/", "PersonServerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:80/person?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PERSONSERVERSERVICE_WSDL_LOCATION = url;
        PERSONSERVERSERVICE_EXCEPTION = e;
    }

    public PersonServerService() {
        super(__getWsdlLocation(), PERSONSERVERSERVICE_QNAME);
    }

    public PersonServerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PERSONSERVERSERVICE_QNAME, features);
    }

    public PersonServerService(URL wsdlLocation) {
        super(wsdlLocation, PERSONSERVERSERVICE_QNAME);
    }

    public PersonServerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PERSONSERVERSERVICE_QNAME, features);
    }

    public PersonServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PersonServerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PersonServer
     */
    @WebEndpoint(name = "PersonServerPort")
    public PersonServer getPersonServerPort() {
        return super.getPort(new QName("http://server.zv2.com.cn/", "PersonServerPort"), PersonServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PersonServer
     */
    @WebEndpoint(name = "PersonServerPort")
    public PersonServer getPersonServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.zv2.com.cn/", "PersonServerPort"), PersonServer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PERSONSERVERSERVICE_EXCEPTION!= null) {
            throw PERSONSERVERSERVICE_EXCEPTION;
        }
        return PERSONSERVERSERVICE_WSDL_LOCATION;
    }

}
