
package cn.com.zv2.stub.person;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import java.util.List;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PersonServer", targetNamespace = "http://server.zv2.com.cn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PersonServer {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "add", targetNamespace = "http://server.zv2.com.cn/", className = "cn.com.zv2.stub.person.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://server.zv2.com.cn/", className = "cn.com.zv2.stub.person.AddResponse")
    @Action(input = "http://server.zv2.com.cn/PersonServer/addRequest", output = "http://server.zv2.com.cn/PersonServer/addResponse")
    public void add(
            @WebParam(name = "arg0", targetNamespace = "")
                    Person arg0);

    /**
     * 
     * @return
     *     returns java.util.List<cn.com.zv2.stub.person.Person>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAll", targetNamespace = "http://server.zv2.com.cn/", className = "cn.com.zv2.stub.person.GetAll")
    @ResponseWrapper(localName = "getAllResponse", targetNamespace = "http://server.zv2.com.cn/", className = "cn.com.zv2.stub.person.GetAllResponse")
    @Action(input = "http://server.zv2.com.cn/PersonServer/getAllRequest", output = "http://server.zv2.com.cn/PersonServer/getAllResponse")
    public List<Person> getAll();

}
